version: "3.0"

# --------------------------- #
#          SERVICES           #
# --------------------------- #

services:
  needys-output-producer:
    build: .
    ports:
      - 8011:8011
    networks:
      - needys

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE:-rabbitmq}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - needys

# --------------------------- #
#           NETWORKS          #
# --------------------------- #

networks:
  needys:
